### ISSUE TITLE
limits.maxplayers McMyAdmin 2.7.0.2

### ISSUE THREAD

**Issue by Fargus5** [BalrogGames/herosfaith#45]
When I start the server the limit of player will be automatically set on 10.
I'm sure to change it in the respective file config like this:

McMyAdmin.conf
https://pastebin.com/SB2v78jY

server.properties
https://pastebin.com/ya1UjuVp

But when I start the server this will happening:
![capture](https://user-images.githubusercontent.com/20026629/36835824-bb6acc7e-1d37-11e8-8316-2d257de6a882.PNG)

I want to precisate that I bought the pro version, but I don't understand why there is no license key in the McMyAdmin Config

**Comment by PhonicUK** [comment]
Does it say Professional Edition in the About tab?

**Comment by PhonicUK** [comment]
This belongs in the Support Board at https://support.cubecoders.com/ - not the issue tracker.

**Comment by Fargus5** [comment]
https://support.cubecoders.com/thread/limits-maxplayers-mcmyadmin/?postbadges=true

**Comment by Fargus5** [comment]
once you're at the directory with McMyAdmin in you run
./MCMA2_Linux_x86_64 +McMyAdmin.LicenceKey YOURLICENCEKEYGOESHERE -configonly
make sure that McMyAdmin is stopped before running that

**Comment by Fargus5** [comment]
contact@cubecoders.com

**Comment by Fargus5** [comment]
resolved
